highlighter: rouge
permalink: pretty
markdown: kramdown
exclude:
  ["Gemfile", "Gemfile.lock", "README.md", "sass", "watch.sh", "style.scss"]
plugins:
  - jekyll-feed
  - jekyll-sitemap

title: chappers
# theme: jekyll-theme-minimal
